Mock up ECE installation options
elastic/docs-builder-example pull request #8
Opened 2024-11-28 02:35 UTC by lcawl

This page plays with content messily ported from https://www.elastic.co/guide/en/cloud-enterprise/current/ece-configure-hosts-ubuntu-onprem.html

2024-12-21 10:10 UTC, Mpdreamz commented on docs/source/elastic/deploy/self-managed/elasticsearch/elasticsearch_targz.md
> +<1> Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
```suggestion
1. Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
```

2024-12-21 10:10 UTC, Mpdreamz commented on docs/source/elastic/deploy/self-managed/elasticsearch/elasticsearch_targz.md
> +<2> This directory is known as `$ES_HOME`.
```suggestion
2. This directory is known as `$ES_HOME`.
```

2024-12-21 10:10 UTC, Mpdreamz commented on docs/source/elastic/deploy/self-managed/elasticsearch/elasticsearch_targz.md
> +<2> This directory is known as `$ES_HOME`.
```suggestion
1. Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
    `elasticsearch-{{version}}-darwin-x86_64.tar.gz: OK`.
2. This directory is known as `$ES_HOME`.
```

2024-12-21 10:12 UTC, Mpdreamz requested changes
Would love to pull this in to get some more real content @lcawl 

Added some suggestions to fix new validation on code callouts:

https://github.com/elastic/docs-builder/pull/118

2025-01-21 01:28 UTC, lcawl commented
> Would love to pull this in to get some more real content @lcawl

Sorry, didn't circle back to this after it served it's purpose for our versioning tests.
Happy to merge now if it's good to go.

2025-01-24 06:29 UTC, closed without merging